### ISSUE TITLE
Run compile and test actions only upon source code changes

### ISSUE THREAD

**Issue by sofian** [SofaPirate/Plaquette#66]
For actions .yml files that deal with code use this header:

```
name: blablabla
on:
  push: # see: https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
    paths:
    - '**.ino'
    - '**.cpp'
    - '**.h'
  pull_request:
```
